### ISSUE TITLE
Support setting any PAPERLESS_ env variables in values.yaml

### ISSUE THREAD

**Issue by andi0b** [CrystalNET-org/helm-paperless-ngx#28]
Thanks for this chart, looks very nice!

I would like to set up paperless-ngx with my existing Postgres database and therefore I would need to load the database settings from external configmaps and secrets.

something like:
``` yaml
# values.yaml
paperless:
  env:
    - name: PAPERLESS_DBENGINE
      value: "postgres"
    - name: PAPERLESS_DBHOST
      valueFrom:
         configMapKeyRef:
           name: bring-your-own-db-config
           key: hostname
    - name: PAPERLESS_DBPASS
      valueFrom:
         secretKeyRef:
           name: bring-your-own-db-secret
           key: pass
```

For other advanced configuration options this would also be a big plus, there are a lot, and I think this chart doesn't need to include them all: https://docs.paperless-ngx.com/configuration/

**Comment by psych0d0g** [comment]
im contemplating here, for external pgsql i would rather implement the same solution as for mysql, so you could set external database connection information through the config datastructure.
and i would also personally prefer implementing any required anvs in that structure to prevent having to define config options in diffrent areas of the chart.
From a user perspective that keeps it more simple.

**Comment by andi0b** [comment]
I went with this chart: https://artifacthub.io/packages/helm/pascaliske/paperless

it’s a bit less sophisticated but allows setting all the things I need without patching the Helm output.

**Comment by psych0d0g** [comment]
happy that you found a chart which works for you, altough this has nothing to do with the topic of this issue, please stay on topic here :)

**Comment by nico151999** [comment]
The problem @andi0b was facing is the same reason why I cannot use this chart for my home lab. If the API would be designed the same way the MariaDB credentials are passed I would still find this problematic since I can think of use cases where database secrets are generated by 3rd party operators which require you to follow their secret keys. So not only defining the secret name but also the secret key would be a necessity in many use cases imo. Otherwise, ugly workarounds like duplicating secrets with different key names using jobs or external secrets operator need to be implemented but I would not recommend this. The solution is allowing more flexibility for the chart users imo.

**Comment by andi0b** [comment]
@nico151999 check my off topic comment, that's probably the solution you're looking for.

**Comment by nico151999** [comment]
@andi0b I checked it and I ended up using yet another chart (oci://ghcr.io/gabe565/charts/paperless-ngx) but this is only temporary. I'd prefer to see this issue fixed here in this repo. So I don't see this issue resolved unfortunately. Using another chart doesn't improve this one. So I'd kindly like to ask the maintainers if it's desired to make according changes.

**Comment by nico151999** [comment]
Thanks for opening it again. Let's hope we'll get a statement from the maintainers :)

**Comment by Tokynet** [comment]
While not exactly the same use case, I am running into the problem below when trying to bring up paperless via this chart on my k0s cluster.

Error:
```shell
k logs paperless-paperless-ngx-6cb5c8f689-hc9kz -c paperless-ngx-consumer
SystemCheckError: System check identified some issues:

ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is set but doesn't exist.
	HINT: Create a directory at /mnt/library/consume
```

Since the container is not coming up at all, I can't even exec into it and manually create the dir.

I can see these defined in the pod's definition:
```yaml
    Environment:
      PAPERLESS_ADMIN_USER:          admin
      PAPERLESS_ADMIN_PASSWORD:      admin
      PAPERLESS_ADMIN_MAIL:          no@mail.cf
      PAPERLESS_DBENGINE:
      PAPERLESS_OCR_LANGUAGES:       deu+eng
      PAPERLESS_CONSUMER_RECURSIVE:  true
      PAPERLESS_CONSUMPTION_DIR:     /mnt/library/consume   <=== 
      PAPERLESS_DATA_DIR:            /var/paperless/data
      PAPERLESS_MEDIA_ROOT:          /mnt/library
      PAPERLESS_LOGGING_DIR:         /var/log/paperless
      PAPERLESS_URL:                 https://paperless.int.DOMAIN
```

If the chart provided a way to pass ENV vars, I could change the path its trying to mount and hopefully get the app deployed.
